### ISSUE TITLE
Pretrained model on ImageNet-1K

### ISSUE THREAD

**Issue by hanoonaR** [amirbar/DETReg#13]
Hi, Thank you for sharing your great work. I am conducting a study on the features of DETReg, and wanted to explore the performance with the pretrained model trained on the full ImageNet. I was wondering if you could share an ImageNet-1K pretrained model? 

Thank you

**Comment by amirbar** [comment]
Hi @hanoonaR,

This model was pretrained on IN-1k:
https://github.com/amirbar/DETReg/releases/download/1.0.0/checkpoint_imagenet.pth

**Comment by hanoonaR** [comment]
Many thanks!

**Comment by hanoonaR** [comment]
Hi @amirbar,
