### ISSUE TITLE
It seems in the pretrain stage the network output 90 categories instead of 2

### ISSUE THREAD

**Issue by 4-0-4-notfound** [amirbar/DETReg#14]
Hello, It seems the network output 90 categories instead of 2, in the pretrain stage.
In the paper, it supposes to output 2 categories (either back gourd or foreground), which is not true in the code.
I'm so confused, Am i missing something?

https://github.com/amirbar/DETReg/blob/490e40403860d51c19333b5db53bcd0ee23647ad/configs/DETReg_top30_in100.sh#L8

https://github.com/amirbar/DETReg/blob/490e40403860d51c19333b5db53bcd0ee23647ad/main.py#L120

https://github.com/amirbar/DETReg/blob/490e40403860d51c19333b5db53bcd0ee23647ad/models/deformable_detr.py#L497-L503

**Comment by amirbar** [comment]
yes, we used 90 as default but practically used category 1 for objectness. If you just want to use the pre-trained model for class agnostic results, you can check out the [colab example](https://colab.research.google.com/drive/1ByFXJClyzNVelS7YdT53_bMbwYeMoeNb#scrollTo=HXEGIgNsJnB4).
