### ISSUE TITLE
Fine Tuning the Model on a fraction of VOC

### ISSUE THREAD

**Issue by mmaaz60** [amirbar/DETReg#15]
Hi @amirbar,

Thank You for the great work. It looks like the parameter `--filter_pct` has never been used in the code. It means the code effectively running fine-tuning on whole VOC/COCO datasets. Please correct me if I am wrong.

Thanks

**Comment by amirbar** [comment]
Hi @mmaaz60,

For COCO `--filter_pct` it is used here:
https://github.com/amirbar/DETReg/blob/490e40403860d51c19333b5db53bcd0ee23647ad/datasets/coco.py#L183

For Pascal you are right, and it seems like I forgot to plug it in this code (it has gone through some refactoring..). Sorry about this! I will submit a fix soon.

Amir

**Comment by mmaaz60** [comment]
Thank You
