### ISSUE TITLE
Reproducing the Results of Table 3 & Table 4

### ISSUE THREAD

**Issue by mmaaz60** [amirbar/DETReg#18]
Hi,

How can I reproduce the results of Table 3 which is about `Few-shot detection performance for the 20
novel categories on the COCO dataset`. 

Also, in Table 4 (`Comparison to semi-supervised detection methods`), it is mentioned in the paper that you pretrained the network on the entire coco train2017 unlabeled images and then fine-tuned on X% of data. But the instructions in README or the corresponding config files load the ImageNet100 pretrained weights for fine-tuning on COCO. Kindly guide me, what process may I follow to reproduce the results reported in Table 4.

Thanks

**Comment by amirbar** [comment]
Hi,

1. Table 3 - I currently don't plan to release the Few-Shot code base (dataloaders, classes, datasplit, etc.) which is based on this [repo](https://github.com/ucbdrive/few-shot-object-detection). 
2. To pretrain on COCO you should set the `--dataset` param to `coco_pretrain` ( see https://github.com/amirbar/DETReg/blob/main/main.py#L366). Also, [here](https://github.com/amirbar/DETReg/releases/download/1.0.0/checkpoint_coco.pth) is the COCO pretraining model checkpoint if this helps. Then, to finetune you need to set the relevant hyperparam described in the paper (epochs, lr, lr drop).

**Comment by usama-axcelerate** [comment]
> 1. Table 3 - I currently don't plan to release the Few-Shot code base (dataloaders, classes, datasplit, etc.) which is based on this [repo](https://github.com/ucbdrive/few-shot-object-detection).

Have you open sourced the few shot code yet?
