### ISSUE TITLE
Missing file (util/plot_utils.py)

### ISSUE THREAD

**Issue by mmaaz60** [amirbar/DETReg#2]
![image](https://user-images.githubusercontent.com/55104795/127581161-a9541d88-8aca-4654-8be4-a08d174b30d2.png)

Hi,

While creating the SS boxes, I am getting the attached error. It looks like the file `util/plot_utils.py` is missing. Please advise. Thanks

**Comment by amirbar** [comment]
Fixed, thanks for opening this issue.
