### ISSUE TITLE
Have you tried using pre-trained RPN to extract proposals?

### ISSUE THREAD

**Issue by Flyooofly** [amirbar/DETReg#32]

**Comment by amirbar** [comment]
I haven't, mainly because I wanted to stick to a setting when no supervision is used.

**Comment by Flyooofly** [comment]
Thanks.But I don't clearly know why p retrained RPN is&nbsp; have&nbsp;&nbsp;supervision&nbsp;,pre trained&nbsp; can't&nbsp; as&nbsp; no&nbsp; suprevision?



---Original---
From: "Amir ***@***.***&gt;
Date: Tue, Dec 28, 2021 16:59 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [amirbar/DETReg] Have you tried using pre-trained RPN to extractproposals? (Issue #32)




 
I haven't, mainly because I wanted to stick to a setting when no supervision is used.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Flyooofly** [comment]
> I haven't, mainly because I wanted to stick to a setting when no supervision is used.

Thank you, but I don’t know why the pre-trained RPN cannot be used as unsupervised. Isn’t pre-training an unsupervised way?

**Comment by amirbar** [comment]
I haven't tried that, but I agree that you may be able to use different ways to generate proposals that might improve on Selective Search psuedo-gt proposals. E.g, as in [here](https://github.com/valeoai/LOST).
