### ISSUE TITLE
ModuleNotFoundError: No module named 'MultiScaleDeformableAttention'

### ISSUE THREAD

**Issue by balurnair** [amirbar/DETReg#33]
Hi, 

I'm getting this error when trying to run the Demo notebook on Colab. Any idea why? Thanks

Edit: I got this working on my local GPU by following the 'Compiling CUDA operators' instructions. But how do you do the same on Colab? Any help is appreciated. Thanks

![image](https://user-images.githubusercontent.com/24573201/148349309-45c711b4-3047-4cc6-a135-6bd52a93eec2.png)

**Comment by balurnair** [comment]
Got the error resolved

**Comment by abhinav3** [comment]
How did you resolve the issue with the colab error. I'm also getting same error.

**Comment by emmanuel-nwogu** [comment]
@balurnair Hi, I'm having the same error in Colab. Please, how did you resolve? The 'Compiling CUDA operators' instructions don't help :(
