### ISSUE TITLE
Release the code for the Airbus ship detection and Few-shot object detection

### ISSUE THREAD

**Issue by 4-0-4-notfound** [amirbar/DETReg#34]
Would you like to release the code for the Airbus Ship Detection and few-shot detection part?

**Comment by amirbar** [comment]
I will release both of them, but it might take some more time. Mainly the FS part. For now, you can follow [this](https://github.com/ucbdrive/few-shot-object-detection) Few-Shot code base (dataloaders, classes, datasplit, etc.) which is enough to reproduce the results.

**Comment by 4-0-4-notfound** [comment]
thx~~

**Comment by amirbar** [comment]
Hello, apologies for dropping the ball here. Unfortunately, we've found an issue in our evaluation pipeline and you are correct. I'm now uploading a new version with a fix and will also make the few-shot checkpoint available. These are the results we are seeing:

evaluation type | Novel AP 10 | Novel AP 30 | Novel AP75 10 | Novel AP75 30
-- | -- | -- | -- | --
Supervised | 12.4 | 20.4 | 13.3 | 21.8
DETReg | 13.7 | 22.6 | 15.1 | 24.3
