### ISSUE TITLE
Did you pretrain DETReg from scratch in Semi-supervised Learning experiment

### ISSUE THREAD

**Issue by 4-0-4-notfound** [amirbar/DETReg#35]
In the Semi-supervised Learning experiment, you said "We pretrain DETReg (Deformable DETR) for 50 epochs on MS COCO train2017 without labels".  

So, did you load the IN1K DETReg pretrain and then pretrain on COCO or just using SwAV as the pretrain and then pretrain on COCO ?

**Comment by amirbar** [comment]
No, just a single pretraining stage on MS COCO.
