### ISSUE TITLE
Results between IN100 and IN1k setting

### ISSUE THREAD

**Issue by 4-0-4-notfound** [amirbar/DETReg#36]
In the arXiv v1 version, the fine-tune result on COCO is 45.5 with IN100 pretrain. But in the arXiv v2 version, it seems the fine-tune result on COCO is still 45.5, but the pretrain dataset is IN1k.  So, in my understanding, with more pretrain data, but the fine-tune result is not improved?

**Comment by amirbar** [comment]
With IN100 the result is only slightly worse compared to IN-1k (45.4 AP compared to 45.5 AP). We report both results in the second version (See Table 1 and Table 4).

**Comment by 4-0-4-notfound** [comment]
Thx~ It's actually in Table 6.      

How about the VOC and Airbus Ship results?  Dose is  all pertained on IN100?
