### ISSUE TITLE
Why the way of getting coco train dataset  is using "build_dataset" rather than "build_selfdet"?

### ISSUE THREAD

**Issue by Flyooofly** [amirbar/DETReg#37]
![image](https://user-images.githubusercontent.com/31236750/151282893-88cbd72a-2f18-4791-b41d-fbbf930ca5c8.png)

**Comment by amirbar** [comment]
The `coco` dataset is intended for supervised finetuning whereas the `coco_pretrain` is intended for DETReg pretraining.
