### ISSUE TITLE
inconsistent description?

### ISSUE THREAD

**Issue by d12306** [amirbar/DETReg#38]
hi, @amirbar , in paper, you describe "We pretrain two variants of DETReg based on DETR [5] and Deformable DETR [71] detectors for 5 and 60 epochs on IN1K and IN100, respectively", are you saying for both in1k and in100 datasets, we pretrain detr for 5 epochs and deformable detr for 60 epochs?

but in the model zoo table of the readme file, i see you pretrain detr for 60 epochs and deformable detr for 5 epochs, is it a typo?

**Comment by amirbar** [comment]
Thank you, I should definitely clarify this. Specifically, the pretraining schedules are as follows:
- Using Deformable-DETR we pretrain DETReg for 50 epochs on IN-100. On IN-1k we only pretrain for 5 epochs.
- Using DETR we pretrain DETReg for 60 epochs on IN-1k.
