### ISSUE TITLE
Question about the  lr_drop in DETR based experiment

### ISSUE THREAD

**Issue by 4-0-4-notfound** [amirbar/DETReg#41]
It seems the ` lr_drop` is missing in the pretraining and finetune script.
The default ` lr_drop`  for DETR is 200, but the pretraining is only 60 epochs,  so  ` lr_drop`  is possible missing.

**Comment by amirbar** [comment]
I think the defaults should be ok. For DETReg using Deformable-DETR on IN1k I did not try lr dropping (just 5e pretraining).  Similarly, for DETReg using DETR on IN I didn't lr drop. On IN100 where I reported some results on the paper, I've lr dropped after 40e and train for 50e.
