### ISSUE TITLE
Which hyperparameters are used in the fewshot setting

### ISSUE THREAD

**Issue by 4-0-4-notfound** [amirbar/DETReg#45]
Hi, what are the `batchsize`, `lr`, `lr_drop`, and `epoch` used in the fewshot setting? 
There are two fewshot experiments,  as shown in Tabel 3 and 4. Please share the hyperparameters for the two experiments.  Many thx~~

**Comment by miznchimaki** [comment]
Maybe DETReg's FSOD hyperparameter is same as Meta-DETR? In his article I saw the author compared DETReg with Meta-DETR more than any others.

**Comment by XuYunqiu** [comment]
Does anyone reproduce the DDETR-ft-full or DETReg-ft-full? Can anyone help me and share the training details?
I tried to reimplement the DDETR-ft-full, but much lower results were achieved.

**Comment by YAOSL98** [comment]
I also want the hyperparameters for fewshot setting.

**Comment by amirbar** [comment]
Hello, apologies for dropping the ball here. Unfortunately, we've found an issue in our evaluation pipeline. I'm now uploading a new version with a fix and will also make the few-shot checkpoint available. These are the results we are seeing:

evaluation type | Novel AP 10 | Novel AP 30 | Novel AP75 10 | Novel AP75 30
-- | -- | -- | -- | --
Supervised | 12.4 | 20.4 | 13.3 | 21.8
DETReg | 13.7 | 22.6 | 15.1 | 24.3
