### ISSUE TITLE
How to plot the gradients

### ISSUE THREAD

**Issue by ver0z** [amirbar/DETReg#46]
Can you help saying how to plot the gradient norms from the unsupervised DETReg detection

**Comment by cjrd** [comment]
Yes - absolutely. I'll add this code + docs in the next week.

**Comment by xiangtaowong** [comment]
> Yes - absolutely. I'll add this code + docs in the next couple of weeks.

looking forward to ur update

**Comment by Flyooofly** [comment]
> Yes - absolutely. I'll add this code + docs in the next couple of weeks.

looking forword to ur update

**Comment by amirbar** [comment]
This should be straightforward to compute (similar to saliency maps). At this point, we will not release this code.
