### ISSUE TITLE
How to run DETReg on video custom dataset ?

### ISSUE THREAD

**Issue by lemyanh2612** [amirbar/DETReg#48]
Could you provide me some feedback about this possibility and some guidance on where is the video custom data loading actually happening so that I could check?

Thank you for your time

**Comment by amirbar** [comment]
Thanks for your interest in our work. In this work, we mainly focused on static images and not videos, although it may be possible to extend this for videos. Are you interested in training DETReg on videos or just running inference on video?

**Comment by lemyanh2612** [comment]
Thank you for your response.
I'm working with the sonar dataset, including the grayscale videos for fish detection [Source](https://www.nature.com/articles/sdata2018190). 

I have tried some models but the results are not very good. 
This link is an [example](https://www.youtube.com/shorts/fonnUdDpjBE) of a sonar dataset. Could you give me some advice?

Thank you for your support.

**Comment by amirbar** [comment]
The most naive idea would be to perform video colorization then run the system as is.
