### ISSUE TITLE
error occured when following the Compiling CUDA operators step.

### ISSUE THREAD

**Issue by ruizhaoz** [amirbar/DETReg#58]
Hello, when I try to run sh ./make.sh by following the Compiling CUDA operators it always show the error, 
Traceback (most recent call last):
  File "setup.py", line 69, in <module>
    ext_modules=get_extensions(),
  File "setup.py", line 47, in get_extensions
    raise NotImplementedError('Cuda is not availabel')
NotImplementedError: Cuda is not availabel

Any idea why this happens? Thanks!

**Comment by ruizhaoz** [comment]
Fixed it.

**Comment by pablopalafox** [comment]
Hey @ruizhaoz, what was the fix? Having similar issues
