### ISSUE TITLE
Only one gpu

### ISSUE THREAD

**Issue by MrCrightH** [amirbar/DETReg#62]
Would you like to share how to train with a single GPU.

**Comment by GDzhu01** [comment]
请问解决了吗

**Comment by GDzhu01** [comment]
我解决了这个问题

**Comment by MrCrightH** [comment]
> 



> 

请问你是如何解决的，如何运行能分享换一下吗

**Comment by GDzhu01** [comment]
加个联系方式吧？

**Comment by MrCrightH** [comment]
你好，请问你的联系方式？微信可以吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "amirbar/DETReg"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月24日(星期一) 晚上8:20
***@***.***&gt;;
抄送:&nbsp;"Mine ***@***.******@***.***&gt;;
主题:&nbsp;Re: [amirbar/DETReg] Only one gpu (Issue #62)





 
加个联系方式吧？

**Comment by GDzhu01** [comment]
uzizz6

**Comment by luoyq6** [comment]
Excuse me, hello. Why do I get the error shown in the picture when I use the command to evaluate? Could you give me some tips?

![b39205ed6c3af39c07dc62491331797](https://user-images.githubusercontent.com/110521846/218691314-d96ea2ac-03d3-4f14-b9ae-5f9225779925.png)
