### ISSUE TITLE
urllib.error.HTTPError: HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by GDzhu01** [amirbar/DETReg#65]
Downloading: "https://dl.fbaipublicfiles.com/deepcluster/swav_800ep_pretrain.pth.tar" to C:\Users\pc/.cache\torch\hub\checkpoints\swav_800ep_pretrain.pth.tar
urllib.error.HTTPError: HTTP Error 403: Forbidden
hope to solve,thanks

**Comment by amirbar** [comment]
seems like an issue in your machine.
