### ISSUE TITLE
getting CUDA error   

### ISSUE THREAD

**Issue by ShreshthaSingh20** [amirbar/DETReg#67]
on running sh ./make.sh I am getting this error. The CUDA_HOME is None because of which it shows "cuda not available" 
![image (8)](https://user-images.githubusercontent.com/63153111/200730149-f20e7896-9dd4-4d59-869e-9d08140fe2af.png)

**Comment by abhinav3** [comment]
Hi Guys, any one open to solve this?

**Comment by amirbar** [comment]
Related to your machine config, you need to set the right CUDA_HOME env param.
