### ISSUE TITLE
Excuse me, hello, the problem occurred during the evaluation

### ISSUE THREAD

**Issue by luoyq6** [amirbar/DETReg#73]
As shown here, An error occurred when I used the command:  ./configs/DETReg_top30_coco.sh --resume exps/DETReg_top30_coco/checkpoint0049.pth --eval
![b39205ed6c3af39c07dc62491331797](https://user-images.githubusercontent.com/110521846/218684405-a7eb8897-401a-4ab8-910d-c66f0783ea99.png)
Can you give me a hint?, thank you

**Comment by amirbar** [comment]
The evaluation script works on MSCoco/Pascal. So you have to use a finetuning pretrained model + config files. E.g:
> ./configs/DETReg_fine_tune_full_coco.sh --<path-to-checkpoint>.pth --eval
