### ISSUE TITLE
Supervised object detection using 1% of labeled data on COCO

### ISSUE THREAD

**Issue by Dopamine0717** [amirbar/DETReg#74]
excuse me, your paper shows that the mAP of supervised object detection using deformable detr using 1% of labeled data on COCO is 11.3, but I only got 9.1. Would you please upload the log of that supervised training and tell me the batch size and the number of gpus you used in that training, thank you very much.

**Comment by amirbar** [comment]
Appologies for the delay, the exact setting is here:
https://github.com/amirbar/DETReg#finetuning-on-mscoco-low-data-regime-from-full-mscoco-pretraining-semi-supervised-learning-setting

This is the log:
[log.txt](https://github.com/amirbar/DETReg/files/12074773/log.txt)
