### ISSUE TITLE
Can you explain clearly how to use a single GPU to train the model and the syntax?

### ISSUE THREAD

**Issue by home56200** [amirbar/DETReg#75]
Hello author :
(1)Train this model using a single GPU, on ImageNet, CoCo, Pascal VOC three data sets, how to implement the training model and what is the grammar?

(2)In your discussion, you only have multiple GPUs to execute the model training syntax. If you modify the multiple GPUs into one GPU, an error will occur. Can you please explain clearly and write it in [ README.md ].

(3) I tried to enter a single GPU execution syntax, which is written as : 
   [ python -u main.py --output_dir /d/Object/DETReg-main/DETReg-main/DETReg_fine_tune_10pct_pascal --dataset voc --filter_pct 0.1 --eval_every 20 --batch_size 2 --epochs 200 --lr_drop 150  ]
This syntax refers to DETReg_fine_tune_10pct_pascal.sh, but an error occurs when only training 1Epoch, the error is as shown in the picture, how to solve it?

![image](https://github.com/amirbar/DETReg/assets/48357577/e8c915a3-2a23-43aa-8425-1782cc14fb56)

Thank you so much~

**Comment by amirbar** [comment]
To finetune on Pascal, you need to follow a similar command to what is present in the config:
GPUS_PER_NODE=2 ./tools/run_dist_launch.sh 2 ./configs/DETReg_fine_tune_10pct_pascal.sh --batch_size 4 --epochs 200 --lr_drop 150

It seems like you are missing one of the arguments from the config.

Also, Training on a single GPU should be possible if you follow the exact command I shared, e.g:
GPUS_PER_NODE=1 ./tools/run_dist_launch.sh 1 ./configs/DETReg_fine_tune_10pct_pascal.sh --batch_size 4 --epochs 200 --lr_drop 150
